[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lendswap = "E4AH1YiTvtnHbqAAX64Sx7sFq892vE64LzFnZYd8yjLE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shivankkapur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
